services:
  zerotier:
    build: .
    container_name: zerotier
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - blockchain_zerotier-data:/var/lib/zerotier-one
      - ../:/app
    working_dir: /app
    command: [ "9bee8941b5431cb5" ]
    restart: unless-stopped

volumes:
  blockchain_zerotier-data:
    external: true

